name: Deploy React site to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Detect where the app actually is (root vs nested folder with a space)
      - name: Detect app directory
        id: detect
        run: |
          if [ -f "package.json" ]; then
            echo "APP_DIR=." >> $GITHUB_ENV
          elif [ -f "portfolio-web-main 2/package.json" ]; then
            echo "APP_DIR=portfolio-web-main 2" >> $GITHUB_ENV
          else
            echo "Could not find package.json at root or in 'portfolio-web-main 2'"; exit 1
          fi
          echo "Using APP_DIR=$GITHUB_ENV"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        working-directory: ${{ env.APP_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.APP_DIR }}

      # SPA refresh fix
      - name: Create 404 for SPA routing
        run: cp build/index.html build/404.html
        working-directory: ${{ env.APP_DIR }}

      # Tell Pages where the built files are
      - name: Set artifact path
        run: echo "BUILDDIR=${{ env.APP_DIR }}/build" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILDDIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
